<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>mp3 – MiniProyecto3</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="MiniProyecto3">
<meta property="og:description" content="Mini proyecto de datos">
<meta property="og:site_name" content="MiniProyecto3">
<meta name="twitter:title" content="MiniProyecto3">
<meta name="twitter:description" content="Mini proyecto de datos">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">MiniProyecto3</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
 <span class="menu-text">Mini Proyecto 3 - Procesamiento de texto</span>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    <div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="mp3.md"><i class="bi bi-file-code"></i>CommonMark</a></li></ul></div></div>
<!-- main -->
<main class="content" id="quarto-document-content">




<p>Mini Proyecto 3 - Procesamiento de texto</p>
<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->
<p>Integrantes:<br>
Jabin Herrera Torres<br>
Priscila Navarrete Campos</p>
<section id="parte-1-carga-y-exploración-de-datos" class="level4">
<h4 class="anchored" data-anchor-id="parte-1-carga-y-exploración-de-datos">Parte 1: Carga y Exploración de Datos</h4>
<p><strong>Carga del Conjunto de Datos</strong></p>
<p>Instalar dependencias</p>
<pre><code>%pip install pandas  
%pip install db-dtype

Importar pandas e importar el dataset

::: {#cell-8 .cell execution_count=52}
``` {.python .cell-code}
import pandas as pd

data_path="../data/datos.csv"

df =pd.read_csv(data_path)
df</code></pre>
<div class="cell-output cell-output-display" data-execution_count="52">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">productAsin</th>
<th data-quarto-table-cell-role="th">country</th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">isVerified</th>
<th data-quarto-table-cell-role="th">ratingScore</th>
<th data-quarto-table-cell-role="th">reviewTitle</th>
<th data-quarto-table-cell-role="th">reviewDescription</th>
<th data-quarto-table-cell-role="th">reviewUrl</th>
<th data-quarto-table-cell-role="th">reviewedIn</th>
<th data-quarto-table-cell-role="th">variant</th>
<th data-quarto-table-cell-role="th">variantAsin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>11-08-2024</td>
<td>True</td>
<td>4</td>
<td>No charger</td>
<td>Every thing is good about iPhones, there's not...</td>
<td>https://www.amazon.in/gp/customer-reviews/R345...</td>
<td>Reviewed in India on 11 August 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>16-08-2024</td>
<td>True</td>
<td>5</td>
<td>iPhone 13 256GB</td>
<td>It look so fabulous, I am android user switche...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2HJ...</td>
<td>Reviewed in India on 16 August 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>14-05-2024</td>
<td>True</td>
<td>4</td>
<td>Flip camera option nill</td>
<td>I tried to flip camera while recording but no ...</td>
<td>https://www.amazon.in/gp/customer-reviews/R3Y7...</td>
<td>Reviewed in India on 14 May 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>24-06-2024</td>
<td>True</td>
<td>5</td>
<td>Product</td>
<td>100% genuine</td>
<td>https://www.amazon.in/gp/customer-reviews/R1P9...</td>
<td>Reviewed in India on 24 June 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>18-05-2024</td>
<td>True</td>
<td>5</td>
<td>Good product</td>
<td>Happy to get the iPhone 13 in Amazon offer</td>
<td>https://www.amazon.in/gp/customer-reviews/R1XI...</td>
<td>Reviewed in India on 18 May 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3057</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>11-10-2023</td>
<td>True</td>
<td>1</td>
<td>Very bad experience with i phone 13</td>
<td>Useless phon never buy this heat n useless cam...</td>
<td>https://www.amazon.in/gp/customer-reviews/R10O...</td>
<td>Reviewed in India on 11 October 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3058</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>14-10-2022</td>
<td>True</td>
<td>2</td>
<td>not happy with this apple product</td>
<td>iam not happy with this product why because ch...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2FW...</td>
<td>Reviewed in India on 14 October 2022</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3059</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>24-02-2022</td>
<td>True</td>
<td>3</td>
<td>Good phone</td>
<td>Good phone</td>
<td>https://www.amazon.in/gp/customer-reviews/R2C7...</td>
<td>Reviewed in India on 24 February 2022</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3060</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>16-10-2023</td>
<td>True</td>
<td>1</td>
<td>Battery discharge</td>
<td>While charging mobile it's getting so hot even...</td>
<td>https://www.amazon.in/gp/customer-reviews/R3K0...</td>
<td>Reviewed in India on 16 October 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3061</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>11-11-2023</td>
<td>True</td>
<td>1</td>
<td>Batter power needs to be improved</td>
<td>Battery power is be very bad need to chat on d...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2QO...</td>
<td>Reviewed in India on 11 November 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
</tr>
</tbody>
</table>

<p>3062 rows × 11 columns</p>
</div>
</div>
<p>:::</p>
<p>Se identifican las columnas reviewDescription que contiene el texto de la reseña y ratingScore que indica la valoracion, segun la valoracion podemos identificar si la reseña es positiva o negativa.</p>
<p><strong>Descripción Inicial de los Datos</strong></p>
<p>Se cuenta la cantidad de reseñas presentes</p>
<div id="cell-12" class="cell" data-execution_count="53">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>num_filas <span class="op">=</span> df.shape[<span class="dv">0</span>]</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"El DataFrame tiene </span><span class="sc">{</span>num_filas<span class="sc">}</span><span class="ss"> filas."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>El DataFrame tiene 3062 filas.</code></pre>
</div>
</div>
<p>El dataframe tiene 3062 reseñas</p>
<p>Ahora veremos si hay mas reseñas positivas o negativas. En nuestro caso, basado en la columna <strong>ratingScore</strong>, positivo sera mayor que 3 y menor o igual a 3 sera negativo. Para diferenciarlo mejor, añadiremos una columna booleana que contendra un <em>Positive</em> o <em>Negative</em>.</p>
<div id="cell-15" class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'ratingPositive'</span>] <span class="op">=</span> df[<span class="st">'ratingScore'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="st">'Positive'</span> <span class="cf">if</span> x <span class="op">&gt;</span> <span class="dv">3</span> <span class="cf">else</span> <span class="st">'Negative'</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>df.to_csv(<span class="st">"../data/datosConColumnaPositivos.csv"</span>,index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="54">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">productAsin</th>
<th data-quarto-table-cell-role="th">country</th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">isVerified</th>
<th data-quarto-table-cell-role="th">ratingScore</th>
<th data-quarto-table-cell-role="th">reviewTitle</th>
<th data-quarto-table-cell-role="th">reviewDescription</th>
<th data-quarto-table-cell-role="th">reviewUrl</th>
<th data-quarto-table-cell-role="th">reviewedIn</th>
<th data-quarto-table-cell-role="th">variant</th>
<th data-quarto-table-cell-role="th">variantAsin</th>
<th data-quarto-table-cell-role="th">ratingPositive</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>11-08-2024</td>
<td>True</td>
<td>4</td>
<td>No charger</td>
<td>Every thing is good about iPhones, there's not...</td>
<td>https://www.amazon.in/gp/customer-reviews/R345...</td>
<td>Reviewed in India on 11 August 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>16-08-2024</td>
<td>True</td>
<td>5</td>
<td>iPhone 13 256GB</td>
<td>It look so fabulous, I am android user switche...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2HJ...</td>
<td>Reviewed in India on 16 August 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>14-05-2024</td>
<td>True</td>
<td>4</td>
<td>Flip camera option nill</td>
<td>I tried to flip camera while recording but no ...</td>
<td>https://www.amazon.in/gp/customer-reviews/R3Y7...</td>
<td>Reviewed in India on 14 May 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>24-06-2024</td>
<td>True</td>
<td>5</td>
<td>Product</td>
<td>100% genuine</td>
<td>https://www.amazon.in/gp/customer-reviews/R1P9...</td>
<td>Reviewed in India on 24 June 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>18-05-2024</td>
<td>True</td>
<td>5</td>
<td>Good product</td>
<td>Happy to get the iPhone 13 in Amazon offer</td>
<td>https://www.amazon.in/gp/customer-reviews/R1XI...</td>
<td>Reviewed in India on 18 May 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3057</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>11-10-2023</td>
<td>True</td>
<td>1</td>
<td>Very bad experience with i phone 13</td>
<td>Useless phon never buy this heat n useless cam...</td>
<td>https://www.amazon.in/gp/customer-reviews/R10O...</td>
<td>Reviewed in India on 11 October 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3058</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>14-10-2022</td>
<td>True</td>
<td>2</td>
<td>not happy with this apple product</td>
<td>iam not happy with this product why because ch...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2FW...</td>
<td>Reviewed in India on 14 October 2022</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3059</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>24-02-2022</td>
<td>True</td>
<td>3</td>
<td>Good phone</td>
<td>Good phone</td>
<td>https://www.amazon.in/gp/customer-reviews/R2C7...</td>
<td>Reviewed in India on 24 February 2022</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3060</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>16-10-2023</td>
<td>True</td>
<td>1</td>
<td>Battery discharge</td>
<td>While charging mobile it's getting so hot even...</td>
<td>https://www.amazon.in/gp/customer-reviews/R3K0...</td>
<td>Reviewed in India on 16 October 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3061</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>11-11-2023</td>
<td>True</td>
<td>1</td>
<td>Batter power needs to be improved</td>
<td>Battery power is be very bad need to chat on d...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2QO...</td>
<td>Reviewed in India on 11 November 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
</tr>
</tbody>
</table>

<p>3062 rows × 12 columns</p>
</div>
</div>
</div>
<p>Contamos la cantidad de <em>Positive</em> y <em>Negative</em></p>
<div id="cell-17" class="cell" data-execution_count="55">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>conteo_positivos_negativos <span class="op">=</span> df[<span class="st">'ratingPositive'</span>].value_counts()</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(conteo_positivos_negativos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ratingPositive
Positive    2065
Negative     997
Name: count, dtype: int64</code></pre>
</div>
</div>
<p>Hay 2065 reseñas positivas y 997 negativas.</p>
</section>
<section id="parte-2-preprocesamiento-de-texto" class="level4">
<h4 class="anchored" data-anchor-id="parte-2-preprocesamiento-de-texto">Parte 2: Preprocesamiento de Texto</h4>
<p><strong>Preprocesamiento del Texto</strong></p>
<p>Instalar spacy</p>
<pre><code>%pip install spacy  
!python -m spacy download en_core_web_sm

Tokenización  
Ademas se quitan espacios vacios y caracteres molestos como "," y "."

::: {#cell-24 .cell execution_count=56}
``` {.python .cell-code}
import spacy

nlp = spacy.load("en_core_web_sm")

df['reviewDescription'] = df['reviewDescription'].fillna('')

df['preprocessedReview'] = ''

df['preprocessedReview'] = df['reviewDescription'].apply(lambda doc: [token.text for token in nlp(doc) if not token.is_punct and not token.is_space and token.text not in ['"', "'"]])

df</code></pre>
<div class="cell-output cell-output-display" data-execution_count="56">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">productAsin</th>
<th data-quarto-table-cell-role="th">country</th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">isVerified</th>
<th data-quarto-table-cell-role="th">ratingScore</th>
<th data-quarto-table-cell-role="th">reviewTitle</th>
<th data-quarto-table-cell-role="th">reviewDescription</th>
<th data-quarto-table-cell-role="th">reviewUrl</th>
<th data-quarto-table-cell-role="th">reviewedIn</th>
<th data-quarto-table-cell-role="th">variant</th>
<th data-quarto-table-cell-role="th">variantAsin</th>
<th data-quarto-table-cell-role="th">ratingPositive</th>
<th data-quarto-table-cell-role="th">preprocessedReview</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>11-08-2024</td>
<td>True</td>
<td>4</td>
<td>No charger</td>
<td>Every thing is good about iPhones, there's not...</td>
<td>https://www.amazon.in/gp/customer-reviews/R345...</td>
<td>Reviewed in India on 11 August 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[Every, thing, is, good, about, iPhones, there...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>16-08-2024</td>
<td>True</td>
<td>5</td>
<td>iPhone 13 256GB</td>
<td>It look so fabulous, I am android user switche...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2HJ...</td>
<td>Reviewed in India on 16 August 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[It, look, so, fabulous, I, am, android, user,...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>14-05-2024</td>
<td>True</td>
<td>4</td>
<td>Flip camera option nill</td>
<td>I tried to flip camera while recording but no ...</td>
<td>https://www.amazon.in/gp/customer-reviews/R3Y7...</td>
<td>Reviewed in India on 14 May 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[I, tried, to, flip, camera, while, recording,...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>24-06-2024</td>
<td>True</td>
<td>5</td>
<td>Product</td>
<td>100% genuine</td>
<td>https://www.amazon.in/gp/customer-reviews/R1P9...</td>
<td>Reviewed in India on 24 June 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[100, genuine]</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>18-05-2024</td>
<td>True</td>
<td>5</td>
<td>Good product</td>
<td>Happy to get the iPhone 13 in Amazon offer</td>
<td>https://www.amazon.in/gp/customer-reviews/R1XI...</td>
<td>Reviewed in India on 18 May 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[Happy, to, get, the, iPhone, 13, in, Amazon, ...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3057</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>11-10-2023</td>
<td>True</td>
<td>1</td>
<td>Very bad experience with i phone 13</td>
<td>Useless phon never buy this heat n useless cam...</td>
<td>https://www.amazon.in/gp/customer-reviews/R10O...</td>
<td>Reviewed in India on 11 October 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[Useless, phon, never, buy, this, heat, n, use...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3058</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>14-10-2022</td>
<td>True</td>
<td>2</td>
<td>not happy with this apple product</td>
<td>iam not happy with this product why because ch...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2FW...</td>
<td>Reviewed in India on 14 October 2022</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[iam, not, happy, with, this, product, why, be...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3059</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>24-02-2022</td>
<td>True</td>
<td>3</td>
<td>Good phone</td>
<td>Good phone</td>
<td>https://www.amazon.in/gp/customer-reviews/R2C7...</td>
<td>Reviewed in India on 24 February 2022</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[Good, phone]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3060</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>16-10-2023</td>
<td>True</td>
<td>1</td>
<td>Battery discharge</td>
<td>While charging mobile it's getting so hot even...</td>
<td>https://www.amazon.in/gp/customer-reviews/R3K0...</td>
<td>Reviewed in India on 16 October 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[While, charging, mobile, it, 's, getting, so,...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3061</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>11-11-2023</td>
<td>True</td>
<td>1</td>
<td>Batter power needs to be improved</td>
<td>Battery power is be very bad need to chat on d...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2QO...</td>
<td>Reviewed in India on 11 November 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[Battery, power, is, be, very, bad, need, to, ...</td>
</tr>
</tbody>
</table>

<p>3062 rows × 13 columns</p>
</div>
</div>
<p>:::</p>
<p>Quitar Stop Words</p>
<div id="cell-26" class="cell" data-execution_count="57">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'preprocessedReview'</span>] <span class="op">=</span> df[<span class="st">'preprocessedReview'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> tokens: [word <span class="cf">for</span> word <span class="kw">in</span> tokens <span class="cf">if</span> <span class="kw">not</span> nlp.vocab[word].is_stop])</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="57">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">productAsin</th>
<th data-quarto-table-cell-role="th">country</th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">isVerified</th>
<th data-quarto-table-cell-role="th">ratingScore</th>
<th data-quarto-table-cell-role="th">reviewTitle</th>
<th data-quarto-table-cell-role="th">reviewDescription</th>
<th data-quarto-table-cell-role="th">reviewUrl</th>
<th data-quarto-table-cell-role="th">reviewedIn</th>
<th data-quarto-table-cell-role="th">variant</th>
<th data-quarto-table-cell-role="th">variantAsin</th>
<th data-quarto-table-cell-role="th">ratingPositive</th>
<th data-quarto-table-cell-role="th">preprocessedReview</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>11-08-2024</td>
<td>True</td>
<td>4</td>
<td>No charger</td>
<td>Every thing is good about iPhones, there's not...</td>
<td>https://www.amazon.in/gp/customer-reviews/R345...</td>
<td>Reviewed in India on 11 August 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[thing, good, iPhones, compared, speed, ios, d...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>16-08-2024</td>
<td>True</td>
<td>5</td>
<td>iPhone 13 256GB</td>
<td>It look so fabulous, I am android user switche...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2HJ...</td>
<td>Reviewed in India on 16 August 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[look, fabulous, android, user, switched, appl...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>14-05-2024</td>
<td>True</td>
<td>4</td>
<td>Flip camera option nill</td>
<td>I tried to flip camera while recording but no ...</td>
<td>https://www.amazon.in/gp/customer-reviews/R3Y7...</td>
<td>Reviewed in India on 14 May 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[tried, flip, camera, recording, facility, add...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>24-06-2024</td>
<td>True</td>
<td>5</td>
<td>Product</td>
<td>100% genuine</td>
<td>https://www.amazon.in/gp/customer-reviews/R1P9...</td>
<td>Reviewed in India on 24 June 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[100, genuine]</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>18-05-2024</td>
<td>True</td>
<td>5</td>
<td>Good product</td>
<td>Happy to get the iPhone 13 in Amazon offer</td>
<td>https://www.amazon.in/gp/customer-reviews/R1XI...</td>
<td>Reviewed in India on 18 May 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[Happy, iPhone, 13, Amazon, offer]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3057</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>11-10-2023</td>
<td>True</td>
<td>1</td>
<td>Very bad experience with i phone 13</td>
<td>Useless phon never buy this heat n useless cam...</td>
<td>https://www.amazon.in/gp/customer-reviews/R10O...</td>
<td>Reviewed in India on 11 October 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[Useless, phon, buy, heat, n, useless, camera,...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3058</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>14-10-2022</td>
<td>True</td>
<td>2</td>
<td>not happy with this apple product</td>
<td>iam not happy with this product why because ch...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2FW...</td>
<td>Reviewed in India on 14 October 2022</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[iam, happy, product, charger, provided, apple...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3059</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>24-02-2022</td>
<td>True</td>
<td>3</td>
<td>Good phone</td>
<td>Good phone</td>
<td>https://www.amazon.in/gp/customer-reviews/R2C7...</td>
<td>Reviewed in India on 24 February 2022</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[Good, phone]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3060</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>16-10-2023</td>
<td>True</td>
<td>1</td>
<td>Battery discharge</td>
<td>While charging mobile it's getting so hot even...</td>
<td>https://www.amazon.in/gp/customer-reviews/R3K0...</td>
<td>Reviewed in India on 16 October 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[charging, mobile, getting, hot, mobile, heated]</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3061</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>11-11-2023</td>
<td>True</td>
<td>1</td>
<td>Batter power needs to be improved</td>
<td>Battery power is be very bad need to chat on d...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2QO...</td>
<td>Reviewed in India on 11 November 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[Battery, power, bad, need, chat, daily, basis...</td>
</tr>
</tbody>
</table>

<p>3062 rows × 13 columns</p>
</div>
</div>
</div>
<p>Lematización</p>
<div id="cell-28" class="cell" data-execution_count="58">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'preprocessedReview'</span>] <span class="op">=</span> df[<span class="st">'preprocessedReview'</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> tokens: [token.lemma_ <span class="cf">for</span> token <span class="kw">in</span> nlp(<span class="st">" "</span>.join(tokens))])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="58">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">productAsin</th>
<th data-quarto-table-cell-role="th">country</th>
<th data-quarto-table-cell-role="th">date</th>
<th data-quarto-table-cell-role="th">isVerified</th>
<th data-quarto-table-cell-role="th">ratingScore</th>
<th data-quarto-table-cell-role="th">reviewTitle</th>
<th data-quarto-table-cell-role="th">reviewDescription</th>
<th data-quarto-table-cell-role="th">reviewUrl</th>
<th data-quarto-table-cell-role="th">reviewedIn</th>
<th data-quarto-table-cell-role="th">variant</th>
<th data-quarto-table-cell-role="th">variantAsin</th>
<th data-quarto-table-cell-role="th">ratingPositive</th>
<th data-quarto-table-cell-role="th">preprocessedReview</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>11-08-2024</td>
<td>True</td>
<td>4</td>
<td>No charger</td>
<td>Every thing is good about iPhones, there's not...</td>
<td>https://www.amazon.in/gp/customer-reviews/R345...</td>
<td>Reviewed in India on 11 August 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[thing, good, iPhones, compare, speed, ios, di...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>16-08-2024</td>
<td>True</td>
<td>5</td>
<td>iPhone 13 256GB</td>
<td>It look so fabulous, I am android user switche...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2HJ...</td>
<td>Reviewed in India on 16 August 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[look, fabulous, android, user, switch, apple,...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>14-05-2024</td>
<td>True</td>
<td>4</td>
<td>Flip camera option nill</td>
<td>I tried to flip camera while recording but no ...</td>
<td>https://www.amazon.in/gp/customer-reviews/R3Y7...</td>
<td>Reviewed in India on 14 May 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[try, flip, camera, recording, facility, add, ...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>24-06-2024</td>
<td>True</td>
<td>5</td>
<td>Product</td>
<td>100% genuine</td>
<td>https://www.amazon.in/gp/customer-reviews/R1P9...</td>
<td>Reviewed in India on 24 June 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[100, genuine]</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>B09G9BL5CP</td>
<td>India</td>
<td>18-05-2024</td>
<td>True</td>
<td>5</td>
<td>Good product</td>
<td>Happy to get the iPhone 13 in Amazon offer</td>
<td>https://www.amazon.in/gp/customer-reviews/R1XI...</td>
<td>Reviewed in India on 18 May 2024</td>
<td>Colour: MidnightSize: 256 GB</td>
<td>B09G9BQS98</td>
<td>Positive</td>
<td>[happy, iPhone, 13, Amazon, offer]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3057</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>11-10-2023</td>
<td>True</td>
<td>1</td>
<td>Very bad experience with i phone 13</td>
<td>Useless phon never buy this heat n useless cam...</td>
<td>https://www.amazon.in/gp/customer-reviews/R10O...</td>
<td>Reviewed in India on 11 October 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[useless, phon, buy, heat, n, useless, camera,...</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3058</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>14-10-2022</td>
<td>True</td>
<td>2</td>
<td>not happy with this apple product</td>
<td>iam not happy with this product why because ch...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2FW...</td>
<td>Reviewed in India on 14 October 2022</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[iam, happy, product, charger, provide, apple,...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3059</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>24-02-2022</td>
<td>True</td>
<td>3</td>
<td>Good phone</td>
<td>Good phone</td>
<td>https://www.amazon.in/gp/customer-reviews/R2C7...</td>
<td>Reviewed in India on 24 February 2022</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[good, phone]</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3060</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>16-10-2023</td>
<td>True</td>
<td>1</td>
<td>Battery discharge</td>
<td>While charging mobile it's getting so hot even...</td>
<td>https://www.amazon.in/gp/customer-reviews/R3K0...</td>
<td>Reviewed in India on 16 October 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[charge, mobile, get, hot, mobile, heated]</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3061</td>
<td>B09G9D8KRQ</td>
<td>India</td>
<td>11-11-2023</td>
<td>True</td>
<td>1</td>
<td>Batter power needs to be improved</td>
<td>Battery power is be very bad need to chat on d...</td>
<td>https://www.amazon.in/gp/customer-reviews/R2QO...</td>
<td>Reviewed in India on 11 November 2023</td>
<td>Colour: (PRODUCT) REDSize: 128 GB</td>
<td>B09G99CW2N</td>
<td>Negative</td>
<td>[battery, power, bad, need, chat, daily, basis...</td>
</tr>
</tbody>
</table>

<p>3062 rows × 13 columns</p>
</div>
</div>
</div>
<p>Las técnicas aplicadas ayudan a limpiar y preparar el texto de la siguiente manera:<br>
<strong>Tokenización</strong>: Divide el texto en palabras individuales (tokens), facilitando el análisis palabra por palabra. Esto permite procesar el texto de manera más estructurada.<br>
<strong>Eliminación de Stop Words</strong>: Remueve palabras comunes que no aportan mucho significado (como “the”, “and”, etc.), permitiendo que el análisis se concentre en palabras más relevantes.<br>
<strong>Lematización</strong>: Reduce las palabras a su forma base o raíz, eliminando variaciones gramaticales (por ejemplo, “running” se convierte en “run”). Esto ayuda a unificar conceptos y mejora la precisión en el análisis.<br>
Estas técnicas son esenciales para eliminar ruido en el texto y convertirlo en una forma más adecuada para el análisis posterior, ademas de reducir el tiempo de lectura y ejecucion del codigo.</p>
</section>
<section id="parte-3-representación-del-texto-con-bag-of-words" class="level4">
<h4 class="anchored" data-anchor-id="parte-3-representación-del-texto-con-bag-of-words">Parte 3: Representación del Texto con Bag of Words</h4>
<p><strong>Bag of Words (BoW)</strong></p>
<p>Instalar scikit-learn</p>
<pre><code>%pip install scikit-learn

::: {#cell-34 .cell execution_count=60}
``` {.python .cell-code}
from sklearn.feature_extraction.text import CountVectorizer

df['preprocessedReviewJoined'] = df['preprocessedReview'].apply(lambda tokens: ' '.join(tokens))

vectorizer = CountVectorizer()

X_bow = vectorizer.fit_transform(df['preprocessedReviewJoined'])

bow_df = pd.DataFrame(X_bow.toarray(), columns=vectorizer.get_feature_names_out())

bow_df</code></pre>
<div class="cell-output cell-output-display" data-execution_count="60">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">00</th>
<th data-quarto-table-cell-role="th">000</th>
<th data-quarto-table-cell-role="th">02</th>
<th data-quarto-table-cell-role="th">03</th>
<th data-quarto-table-cell-role="th">05</th>
<th data-quarto-table-cell-role="th">06</th>
<th data-quarto-table-cell-role="th">09</th>
<th data-quarto-table-cell-role="th">0display</th>
<th data-quarto-table-cell-role="th">10</th>
<th data-quarto-table-cell-role="th">100</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">लत</th>
<th data-quarto-table-cell-role="th">वत</th>
<th data-quarto-table-cell-role="th">सम</th>
<th data-quarto-table-cell-role="th">समजत</th>
<th data-quarto-table-cell-role="th">समय</th>
<th data-quarto-table-cell-role="th">सर</th>
<th data-quarto-table-cell-role="th">सह</th>
<th data-quarto-table-cell-role="th">हक</th>
<th data-quarto-table-cell-role="th">हकश</th>
<th data-quarto-table-cell-role="th">हर</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3057</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3058</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3059</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3060</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">3061</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>...</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>

<p>3062 rows × 5375 columns</p>
</div>
</div>
<p>:::</p>
<div id="cell-35" class="cell" data-execution_count="61">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>bow_df.to_csv(<span class="st">"../data/bow.csv"</span>,index<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Bag of Words (BoW) basicamente convirtio las reseñas preprocesadas (columna preprocessedReview) en vectores numéricos. Cada reseña es transformada en una fila de la matriz, donde cada columna representa una palabra del vocabulario total de las reseñas. El valor en cada celda indica cuántas veces aparece esa palabra en la reseña específica. BoW es importante porque convierte texto en una representación numérica, es simple porque solo cuenta la frecuencia de palabras sin considerar el orden, y es eficaz al crear una matriz numérica fácil de interpretar y procesar por algoritmos de machine learning.</p>
</section>
<section id="parte-4-implementación-de-clasificadores" class="level4">
<h4 class="anchored" data-anchor-id="parte-4-implementación-de-clasificadores">Parte 4: Implementación de Clasificadores</h4>
<p><strong>Clasificador Naive Bayes</strong></p>
<div id="cell-39" class="cell" data-execution_count="62">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.naive_bayes <span class="im">import</span> MultinomialNB</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(X_bow, df[<span class="st">'ratingPositive'</span>], test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>nb_classifier <span class="op">=</span> MultinomialNB()</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>nb_classifier.fit(X_train, y_train)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> nb_classifier.predict(X_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Evaluar rendimiento</p>
<div id="cell-41" class="cell" data-execution_count="63">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> classification_report</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>report <span class="op">=</span> classification_report(y_test, y_pred, target_names<span class="op">=</span>[<span class="st">'Negative'</span>, <span class="st">'Positive'</span>])</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(report)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              precision    recall  f1-score   support

    Negative       0.81      0.70      0.75       183
    Positive       0.88      0.93      0.90       430

    accuracy                           0.86       613
   macro avg       0.84      0.81      0.83       613
weighted avg       0.86      0.86      0.86       613
</code></pre>
</div>
</div>
<p>Al parecer el modelo es más preciso al predecir reseñas positivas (88%) que negativas (81%). por otra paerte tiene un buen recall de 93% para las reseñas positivas, a diferencia de un recall menor para las reseñas negativas (70%). El modelo tiene una precisión general del 86% seun el accuracy.En general, el modelo tiene un mejor desempeño en las reseñas positivas que en las negativas. Esto puede deberse a un mayor número de reseñas positivas en el conjunto de datos (430 frente a 183).</p>
<p><strong>Regresión Logística</strong></p>
<div id="cell-44" class="cell" data-execution_count="64">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> classification_report</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> X_bow</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'ratingPositive'</span>]</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.3</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>logistic_model <span class="op">=</span> LogisticRegression(max_iter<span class="op">=</span><span class="dv">1000</span>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>logistic_model.fit(X_train, y_train)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> logistic_model.predict(X_test)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(classification_report(y_test, y_pred))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              precision    recall  f1-score   support

    Negative       0.86      0.66      0.75       281
    Positive       0.86      0.95      0.91       638

    accuracy                           0.86       919
   macro avg       0.86      0.81      0.83       919
weighted avg       0.86      0.86      0.86       919
</code></pre>
</div>
</div>
<p>El modelo de Regresión Logística muestra un rendimiento similar al de Naive Bayes, con una precisión del 86% para ambas clases, positivas y negativas. Sin embargo, tiene un mejor recall para las reseñas positivas (95%) en comparación con las negativas (66%), lo que sugiere que identifica mejor las reseñas positivas. El F1-score también refleja un mejor balance para las reseñas positivas (91%) frente al 75% para las negativas. En general, el modelo tiene una precisión global del 86% y, al igual que Naive Bayes, se desempeña mejor en la clasificación de reseñas positivas, lo que probablemente se deba a la mayor cantidad de ejemplos positivos (638 frente a 281 negativos) en el conjunto de datos.</p>
</section>
<section id="parte-5-análisis-y-conclusión" class="level4">
<h4 class="anchored" data-anchor-id="parte-5-análisis-y-conclusión">Parte 5: Análisis y Conclusión</h4>
<p><strong>Análisis de Resultados</strong></p>
<p>Comparando los resultados de Naive Bayes y Regresión Logística:</p>
<p><strong>Precisión</strong>:<br>
Ambos modelos tienen precisión similar. En el caso de los valores negativos, el modelo de regresión logística tiene una precisión ligeramente mejor (0.86 frente a 0.81).</p>
<p>Para los valores positivos, ambos modelos tienen la misma precisión (0.86-0.88).</p>
<p><strong>Recall</strong>:<br>
En la categoría negativa, Naive Bayes tiene mejor recall (0.70 frente a 0.66).</p>
<p>Para los valores positivos, la regresión logística tiene mejor recall (0.95 frente a 0.93), lo que significa que identifica más correctamente las instancias positivas.</p>
<p><strong>F1-Score</strong>:<br>
El F1-Score, que combina la precisión y el recall, es ligeramente mejor para la regresión logística en los valores positivos (0.91 frente a 0.90). Por otra parte, en los valores negativos, tienen igual desempeño (0.75 frente a 0.75).</p>
<p><strong>Conclusión</strong>:<br>
Naive Bayes es más equilibrado en identificar tanto negativos como positivos, aunque tiene un menor recall para positivos. Regresión Logística sobresale en identificar correctamente los positivos con un recall más alto, pero pierde algo de precisión en la clase negativa.</p>
<p>En general, Regresión Logística parece ser mejor para maximizar la detección de positivos, mientras que Naive Bayes es más equilibrado en ambas clases.</p>
<p><strong>Métodos de mejora sugeridos</strong></p>
<p>Mejor Preprocesamiento</p>
<ol type="1">
<li>Normalización o Escalado: Los modelos como la regresión logística suelen beneficiarse de la normalización de los datos. Escalar las características podría mejorar su desempeño.<br>
</li>
<li>Textos Limpios y Consistentes: Considerar el uso de técnicas más avanzadas para limpiar los textos, como eliminar palabras muy comunes y no informativas.<br>
</li>
<li>N-gramas: Usar n-gramas (combinaciones de palabras) en lugar de palabras individuales podría capturar mejor el contexto en las reseñas, lo que puede mejorar el modelo.</li>
</ol>
<p>Mejoras en el Modelo:</p>
<ol type="1">
<li>Hiperparámetros: Ajustar hiperparámetros, como la regularización en la regresión logística o suavizado en Naive Bayes, podría mejorar los resultados.</li>
<li>Ensamble de Modelos: Se podría explorar un ensamble de ambos modelos (Naive Bayes + Regresión Logística) para aprovechar las fortalezas de cada uno.</li>
<li>Modelos más avanzados: Explorar otros algoritmos de clasificación, como máquinas de soporte vectorial (SVM) o redes neuronales, podría mejorar el desempeño.</li>
</ol>
<p><a href="https://jabinherrera.github.io/MiniProyecto3/mp3.html">HTML de la pagina desplegada</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/jabinherrera\.github\.io\/MiniProyecto3");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions"><ul><li><a href="https://github.com/jabinherrera/MiniProyecto3/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>