# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MiniProyecto3',
                'doc_host': 'https://jabinherrera.github.io',
                'git_url': 'https://github.com/jabinherrera/MiniProyecto3',
                'lib_path': 'MiniProyecto3'},
  'syms': {'MiniProyecto3.core': {'MiniProyecto3.core.foo': ('core.html#foo', 'MiniProyecto3/core.py')}}}
